spring.application.name=Reservation Service
server.port=8082

spring.datasource.url=${RESERVATION_DB_URL}
spring.datasource.username=${AUTH_DB_USER}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration

